### PR TITLE
Fixes #2810: correct look of hidden-inset windows in full screen.

### LINKED ISSUE #2810: BrowserWindow 'title-bar-style': 'hidden-inset' option doesn't work correctly in fullscreen
Origintal ticket: https://github.com/sindresorhus/caprine/issues/5

-

In fullscreen mode, instead of showing the user toolbar, it covers it up with a gray frame.

#### 1. Normal

screen shot 2015-09-17 at 10 15 09

#### 2. Fullscreen

screen shot 2015-09-17 at 10 15 37

#### 3. Fullscreen with menubar visible

screen shot 2015-09-17 at 10 15 56

Ideally it would show the top (covered up) web content in both 2. and 3., so my custom toolbar would be visible there.

-

OS X 10.10 and Electron 0.32.3.

-

@jaanus

### PR DESCRIPTION
**Pull request by jaanus**
`hidden` and `hidden-inset` windows differ only by the hidden-inset window having a toolbar. Yet, the toolbar yields an incorrect look in fullscreen mode. So, we hide and recreate the toolbar for such windows when going to/from fullscreen.

There are some visible artifacts during the fullscreen animations, as the toolbar gets created and destroyed. When entering fullscreen, you see a toolbar that then disappears. When going back to normal window, you see the traffic light buttons jump around a little bit. Yet, this is definitely better than the current broken fullscreen look.

### CODE REVIEW

File: atom/browser/native_window_mac.h [hunk 1]
```diff
@@ -78,6 +78,8 @@ class NativeWindowMac : public NativeWindow {
     UpdateDraggableRegionViews(draggable_regions_);
   }
 
+  bool should_hide_native_toolbar_in_fullscreen_;
```
Comment (zcbenz) [inline atom/browser/native_window_mac.h]: The Google C++ style guide which Electron's code follows forbids public member datas, it has to be put in to private section and we can add a public getter for it. You can reference how we deal with `force_using_draggable_region_` in `native_window.h`.

Comment (jaanus) [inline atom/browser/native_window_mac.h]: Cool, I’ll fix the PR later today.

**Comment by zcbenz** [comment]
Thanks!
