### PR TITLE
session: using storageparttion to retrieve requestcontext

### LINKED ISSUE #2050: resolveProxy immediately on app ready event causes app to segfault on OS X
This code causes a segmentation fault:

```
app.once('ready', function() {
   app.resolveProxy('https://google.com', function(proxyURL) {
     console.log('proxyURL is', proxyURL);
   });
});
```

This code does not:
```
app.once('ready', function() {
   setTimeout(function() {
     app.resolveProxy('https://google.com', function(proxyURL) {
       console.log('proxyURL is', proxyURL);
     });
   }, 0);
});
```

This code is also fine:
```
app.once('ready', function() {
   setImmediate(function() {
     app.resolveProxy('https://google.com', function(proxyURL) {
       console.log('proxyURL is', proxyURL);
     });
   });
});
```

Here is the barf from the crash dialog: https://gist.github.com/davidbanham/7e4ab9e54f2706554f01

I have confirmed this on both v0.28.3 and v0.28.1

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #2050 is this problem with node integration that `resolveproxy` call made earlier than initialising `url_request_context_getter` ?

Also based on suggestion [here](https://code.google.com/p/chromium/codesearch#chromium/src/net/url_request/url_request_context_getter.h&q=geturlrequestcontext&sq=package:chromium&l=30) moved `GetURLRequestContext` to network task runner.

### CODE REVIEW

File: atom/browser/api/atom_api_session.cc [hunk 1]
```diff
@@ -29,35 +32,64 @@ class ResolveProxyHelper {
...
-        &pac_req_, nullptr, net::BoundNetLog());
-
-    // Completed synchronously.
-    if (result != net::ERR_IO_PENDING)
-      OnResolveProxyCompleted(result);
+      : callback_(callback),
+        origin_thread_(base::ThreadTaskRunnerHandle::Get()),
+        weak_ptr_factory_(this) {
+    scoped_refptr<net::URLRequestContextGetter> getter =
+        browser_context->GetDefaultStoragePartition(browser_context)
```
Comment (zcbenz) [inline atom/browser/api/atom_api_session.cc]: You can just call `browser_context->GetRequestContext()`.

File: atom/browser/api/atom_api_session.cc [hunk 2]
```diff
@@ -29,35 +32,64 @@ class ResolveProxyHelper {
...
+  void OnResolveProxyCompleted(
+      scoped_refptr<base::SingleThreadTaskRunner> origin_thread,
+      int result) {
     std::string proxy;
     if (result == net::OK)
       proxy = proxy_info_.ToPacString();
-    callback_.Run(proxy);
+    origin_thread->PostTask(FROM_HERE,
+                            base::Bind(callback_,
+                                       proxy));
```
Comment (zcbenz) [inline atom/browser/api/atom_api_session.cc]: No need to put this in a new line.

File: atom/browser/api/atom_api_session.cc [hunk 3]
```diff
@@ -29,35 +32,64 @@ class ResolveProxyHelper {
...
 
-    delete this;
+    weak_ptr_factory_.InvalidateWeakPtrs();;
```
Comment (zcbenz) [inline atom/browser/api/atom_api_session.cc]: `InvalidateWeakPtrs` does not free memory, we still need to `delete this`.

File: atom/browser/api/atom_api_session.cc [hunk 4]
```diff
@@ -29,35 +32,64 @@ class ResolveProxyHelper {
...
+                   origin_thread);
+
+    // Start the request.
+    int result = proxy_service->ResolveProxy(
+        url, net::LOAD_NORMAL, &proxy_info_, callback,
+        &pac_req_, nullptr, net::BoundNetLog());
+
+    // Completed synchronously.
+    if (result != net::ERR_IO_PENDING)
+      callback.Run(result);
```
Comment (zcbenz) [inline atom/browser/api/atom_api_session.cc]: `callback` should run in original thread.

File: atom/browser/api/atom_api_session.cc [hunk 5]
```diff
@@ -29,35 +32,64 @@ class ResolveProxyHelper {
...
+    scoped_refptr<net::URLRequestContextGetter> getter =
+        browser_context->GetDefaultStoragePartition(browser_context)
+            ->GetURLRequestContext();
+
+    getter->GetNetworkTaskRunner()->PostTask(
+        FROM_HERE,
+        base::Bind(&ResolveProxyHelper::ResolveProxy,
+                   weak_ptr_factory_.GetWeakPtr(),
+                   getter, url,
+                   origin_thread_));
```
Comment (zcbenz) [inline atom/browser/api/atom_api_session.cc]: We don't need to pass `origin_thread_` since it is already a data member.

File: atom/browser/api/atom_api_session.cc (hunk 1 above)
Comment (deepak1556) [inline atom/browser/api/atom_api_session.cc]: `GetRequestContext` is private in brightray.

File: atom/browser/api/atom_api_session.cc [hunk 6]
```diff
@@ -29,35 +32,59 @@ class ResolveProxyHelper {
...
+                   getter, url));
   }
 
   void OnResolveProxyCompleted(int result) {
     std::string proxy;
     if (result == net::OK)
       proxy = proxy_info_.ToPacString();
-    callback_.Run(proxy);
+    original_thread_->PostTask(FROM_HERE,
+                               base::Bind(callback_, proxy));
```
Comment (deepak1556) [inline atom/browser/api/atom_api_session.cc]: @zcbenz `callback_` runs in the original thread here.

**Comment by deepak1556** [comment]
Fixed, thanks!

File: atom/browser/api/atom_api_session.cc [hunk 7]
```diff
@@ -29,35 +32,59 @@ class ResolveProxyHelper {
...
 
+    weak_ptr_factory_.InvalidateWeakPtrs();
```
Comment (zcbenz) [inline atom/browser/api/atom_api_session.cc]: `InvalidateWeakPtrs` is called in destructor so no need to call it here.

Comment (deepak1556) [inline atom/browser/api/atom_api_session.cc]: Fixed.

**Comment by zcbenz** [comment]
:+1:
