### PR TITLE
browser: emit did-fail-load for invalid url

### LINKED ISSUE #4342: Warn for invalid URL
Hi, I'm not exactly sure if this is a bug, but after reading [this article](https://samsaffron.com/archive/2012/06/07/testing-3-million-hyperlinks-lessons-learned), I tried the nonsense url mentioned in the comments `http://nonsense:port/yay` with loadUrl and while it didn't crash electron, none of the regular browserWindow or webContent events seemed to be emitted. 

If you use a url that isn't available e.g. `http://lszfief78nwfo8dosz8nfeosz8jeosz8t.com`, you get the regular did-start-loading, did-fail-load etc. emitted, but there's no error or events emitted for `http://nonsense:port/yay`

I've created a temp repo to try it out: https://github.com/Darkle/loadUrlTest

(sorry for the unspecific issue title, I didn't know what else to call it)

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #4342

### CODE REVIEW

File: spec/api-browser-window-spec.js [hunk 1]
```diff
@@ -94,12 +94,19 @@ describe('browser-window module', function() {
       });
       return w.loadURL('about:blank');
     });
-    return it('should emit did-fail-load event', function(done) {
+    it('should emit did-fail-load event', function(done) {
```
Comment (kevinsawicki) [inline spec/api-browser-window-spec.js]: Should this message be updated now to be more specific for which failure case it is testing?

Like `'should emit did-fail-load-event for files that do not exist'` or `'should emit did-fail-load-event for URLs that 404'`?

Comment (deepak1556) [inline spec/api-browser-window-spec.js]: Fixed, thanks!

**Comment by zcbenz** [comment]
Thanks!
