### PR TITLE
process: add hang method

### LINKED ISSUE #1933: process.crash() equivalent to trigger "unresponsive" event
Chromium provides some debug URLs listed under `chrome://chrome-urls/`. Some of them are `chrome://crash`, `chrome://kill` and `chrome://hang`.

"crash" and "kill" seem do be doing the same and in Electron we can trigger a crash using `process.crash()`. But for "hang" which makes Chromium freeze and pop-up the "Unresponsive" dialog there currently seems to be no method to trigger this.

It would be very useful for Electron apps that have to handle unresponsive windows if they could somehow purposely make the window unresponsive (so that it triggers the `unresponsive` event) in order to test the behavior. Maybe `process.hang()` or `process.unresponsive()`.

While I'm not very good at C++ I did some research and found that Chromium achieves this by doing

```c++
for (;;) {
  base::PlatformThread::Sleep(base::TimeDelta::FromSeconds(1));
}
```

[in render_frame_impl.cc](https://chromium.googlesource.com/chromium/src.git/+/master/content/renderer/render_frame_impl.cc) between lines 353 and 355.

Electron seems to register the `process.crash()` method [here](https://github.com/atom/electron/blob/71598e15bf0ca2fd8de338d864cc37776608c6c2/atom/common/api/atom_bindings.cc#L56). Maybe a `hang()` method could be added the same way?

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #1933

### CODE REVIEW

File: atom/common/api/atom_bindings.cc [hunk 1]
```diff
@@ -26,6 +28,12 @@ void Crash() {
   static_cast<DummyClass*>(NULL)->crash = true;
 }
 
+void Hang() {
+  // Temporarily access the current thread.
+  base::ThreadRestrictions::ScopedAllowSingleton allow_singleton;
+  base::WaitableEvent(false, false).Wait();
```
Comment (zcbenz) [inline atom/common/api/atom_bindings.cc]: Why not just use `base::PlatformThread::Sleep`? The `base::ThreadRestrictions::ScopedAllowSingleton` call makes this code quite confusing at first glance.

File: docs/api/process.md [hunk 2]
```diff
@@ -7,3 +7,7 @@ upstream node:
 * `process.versions['electron']` String - Version of Electron.
 * `process.versions['chrome']` String - Version of Chromium.
 * `process.resourcesPath` String - Path to JavaScript source code.
+
+## process.hang
+
+Call in the `renderer` process to trigger `unresponsive` event.
```
Comment (zcbenz) [inline docs/api/process.md]: It can also be called in the main process.

Comment (deepak1556) [inline docs/api/process.md]: But there wont any browserwindow creation at all for the event to be triggered, which i believed to be the use of this method ?

File: atom/common/api/atom_bindings.cc (hunk 1 above)
Comment (deepak1556) [inline atom/common/api/atom_bindings.cc]: to make the UI thread to hang specifically.

Comment (zcbenz) [inline atom/common/api/atom_bindings.cc]: Are you sure `ScopedAllowSingleton` should be used instead of `ScopedAllowIO`? And the `"Temporarily access the current thread."` sounds meaningless.

File: docs/api/process.md (hunk 2 above)
Comment (zcbenz) [inline docs/api/process.md]: It sill needs to be clear in document, otherwise people would just call it in the main process and hope the renderer process to hang. Just say something like "Makes the main thread of current process hang" is enough.

File: atom/common/api/atom_bindings.cc (hunk 1 above)
Comment (deepak1556) [inline atom/common/api/atom_bindings.cc]: if the call is gonna be made on the UI thread , accessing the current thread is the right way ? thats why went with [ScopedAllowSingleton](https://code.google.com/p/chromium/codesearch#chromium/src/base/threading/thread_restrictions.h&q=threadrestrictions&sq=package:chromium&l=121) though it states `doing it is almost always incorrect` .

Comment (zcbenz) [inline atom/common/api/atom_bindings.cc]: What do you mean by "accessing the current thread"?

Comment (deepak1556) [inline atom/common/api/atom_bindings.cc]: my understanding was `unresponsive` event on renderer gets triggered when UI thread hangs. So to simulate it, causing a indefinite wait event on UI thread ?

Comment (zcbenz) [inline atom/common/api/atom_bindings.cc]: But why using `ScopedAllowSingleton`?

Comment (deepak1556) [inline atom/common/api/atom_bindings.cc]: using it based on usage in `BrowserThread_CurrentlyOn` method. Can just create an indefinite event ?

Comment (zcbenz) [inline atom/common/api/atom_bindings.cc]: Why does it have any connection with `BrowserThread_CurrentlyOn`?

Comment (deepak1556) [inline atom/common/api/atom_bindings.cc]: didnt know the right way of usage

Comment (zcbenz) [inline atom/common/api/atom_bindings.cc]: Then just don't call unrelated code unless you know what it means.

Comment (deepak1556) [inline atom/common/api/atom_bindings.cc]: have fixed it. sorry.

**Comment by zcbenz** [comment]
:+1:
