### PR TITLE
browser: fix document.hidden value

### LINKED ISSUE #3788: visibilitychange event not being triggered
I've been trying to use the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) however the `visibilitychange` event is not being triggered. 

I understand that Electron's `pageVisibility` option forces either visible or hidden states but is there a way to listen for the true window visibility changes?

P.S.: Here's a small snippet and an [electron-quick-start fork](https://github.com/zenorocha/electron-quick-start/blob/master/index.html) if you guys wanna do some testing.

```js
document.addEventListener("visibilitychange", function() {
  console.log( document.visibilityState );
});
```

### PR DESCRIPTION
**Pull request by deepak1556**
As @paulcbetts noted, users can emulate the behviour with blur/focus events (actually they should use these instead). Anyways just fixing for compatibility. Also have fixed the value of `document.hidden` being incorrect.

### CODE REVIEW

**Comment by paulcbetts** [comment]
:+1:

**Comment by zcbenz** [comment]
Calling `WasHidden()` will have lots of side effects, we used to call it in `Hide()` but then reverted the change because of the unexpected side effects, see also #2935 and https://github.com/atom/atom/pull/8779.

**Comment by deepak1556** [comment]
Have to find a better way then. Have modified the PR to address only the value returned by `document.hidden` to consider both visibility and focus as variables.

File: atom/renderer/lib/override.coffee [hunk 1]
```diff
@@ -118,6 +118,12 @@ Object.defineProperty window.history, 'length',
   get: ->
     getHistoryOperation 'length'
 
-# Make document.hidden return the correct value.
+# Make document.hidden and document.visibilityState return the correct value.
 Object.defineProperty document, 'hidden',
-  get: -> !remote.getCurrentWindow().isVisible()
+  get: ->
+    currentWindow = remote.getCurrentWindow()
+    !currentWindow.isFocused() || !currentWindow.isVisible()
```
Comment (zcbenz) [inline atom/renderer/lib/override.coffee]: Window without focus can also be visible, we should check `isMinimized` instead of `isFocused`.

Comment (deepak1556) [inline atom/renderer/lib/override.coffee]: Updated. One doubt though, isnt the situation of non-minimized, non-focused, visible window same as a backgrounded tab ? Shouldnt the value of `document.hidden` be true in this case ?

But yeah, users can always override this with what they see fit as variables, we can just leave it at minimize and visibility, i guess.

**Comment by zcbenz** [comment]
> One doubt though, isnt the situation of non-minimized, non-focused, visible window same as a backgrounded tab ? Shouldnt the value of document.hidden be true in this case ?

We should follow the behavior of a one-tab Chrome browser window, instead of background tabs.

**Comment by zcbenz** [comment]
:+1:

File: atom/renderer/lib/override.coffee [hunk 2]
```diff
@@ -118,6 +118,12 @@ Object.defineProperty window.history, 'length',
   get: ->
     getHistoryOperation 'length'
 
-# Make document.hidden return the correct value.
+# Make document.hidden and document.visibilityState return the correct value.
 Object.defineProperty document, 'hidden',
-  get: -> !remote.getCurrentWindow().isVisible()
+  get: ->
+    currentWindow = remote.getCurrentWindow()
```
Comment (bbondy) [inline atom/renderer/lib/override.coffee]: This is sometimes returning null

File: atom/renderer/lib/override.coffee [hunk 3]
```diff
@@ -118,6 +118,12 @@ Object.defineProperty window.history, 'length',
...
+    currentWindow.isMinimized() || !currentWindow.isVisible()
```
Comment (bbondy) [inline atom/renderer/lib/override.coffee]: Causing this to fail and then other things don't work right.
