### PR TITLE
browser: creating download manager delegate to handle downloads

### LINKED ISSUE #1909: Download attribute on link elements not working inside of webview
Thanks for the nice project, folks.

I'm using electron to wrap our web application in a webview and distribute this application this way.

Unfortunately we discovered that links with the `download` attribute don't work.

E.g. http://davidwalsh.name/demo/html5-download.php

Works perfectly fine in Chrome but unfortunately does not inside of the webview in electron.

I digged the issues already and couldn't find any information on this specific case.

Any ideas on this are more than welcome. :bowtie: 

Thanks. :)

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #1909 

this basic implemetation provides ability to save downloads, the default download directory points to `Downloads` folder in the respective app. We can provide api around this for users track status of each download by adding [observers](https://code.google.com/p/chromium/codesearch#chromium/src/content/public/browser/download_item.h&sq=package:chromium&rcl=1434958068&l=87) to this class, it deserves a separate PR. Thoughts ?

### CODE REVIEW

**Comment by hokein** [comment]
We may add `Download` APIs like 
```
downloads.download({url: "", download_dir:"", file_name""}, function(error, downloadId) {})
downloads.pause(downloadId, callback)
downloads.resume(downloadId, callback)
downloads.cancel(downloadId, callback)
downloads.show(downloadId)
```
But I wonder it's worthy adding this. Not sure whether it's a desirable feature that most developers need.

**Comment by deepak1556** [comment]
> But I wonder it's worthy adding this. Not sure whether it's a desirable feature that most developers need.

Just so they can provide their own UI for download progress, or alteast get notifed of the downloads status.

I am +1 on that api, will wait for others suggestion and get it as a separate PR. Thanks!

**Comment by steelbrain** [comment]
:heart:

**Comment by steelbrain** [comment]
and instead of the API @hokein suggested, how about
```js
type Progress = shape(
  TotalBytes => string,
  RecievedBytes => string
)
class Downloads{
  static setSavePath(path: String): void
  static download(path: String[, savePath: String]): Download
}
class Download extends EventEmitter{
  savePath: String
  onComplete(Callback: function(): void): void
  onProgress(Callback: function(Progress): void): void
  onAbort(Callback: function(hadError: bool): void): void
  pause(): void
  cancel()
}
```

File: atom/browser/atom_download_manager_delegate.cc [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+}
+
+void AtomDownloadManagerDelegate::OnDownloadPathGenerated(
+    uint32 download_id,
+    const content::DownloadTargetCallback& callback,
+    const base::FilePath& default_path) {
+  DCHECK_CURRENTLY_ON(content::BrowserThread::UI);
+
+  auto item = download_manager_->GetDownload(download_id);
+  if (!item || (item->GetState() != content::DownloadItem::IN_PROGRESS))
```
Comment (zcbenz) [inline atom/browser/atom_download_manager_delegate.cc]: This condition should never be true.

File: atom/browser/atom_download_manager_delegate.cc [hunk 2]
```diff
@@ -0,0 +1,134 @@
...
+    return;
+
+  file_dialog::Filters filters;
+  base::FilePath path;
+  if (!file_dialog::ShowSaveDialog(
+          nullptr, item->GetURL().spec(),
```
Comment (zcbenz) [inline atom/browser/atom_download_manager_delegate.cc]: Should find out the `BrowserWindow` that started the download and use it as parent window.

File: atom/browser/atom_download_manager_delegate.cc [hunk 3]
```diff
@@ -0,0 +1,134 @@
...
+}
+
+bool AtomDownloadManagerDelegate::DetermineDownloadTarget(
+    content::DownloadItem* download,
+    const content::DownloadTargetCallback& callback) {
+  DCHECK_CURRENTLY_ON(content::BrowserThread::UI);
+
+  if (default_download_path_.empty()) {
+    default_download_path_ = download_manager_->GetBrowserContext()
+                                ->GetPath().Append(
```
Comment (zcbenz) [inline atom/browser/atom_download_manager_delegate.cc]: Lines not aligned.

File: atom/browser/atom_download_manager_delegate.cc [hunk 4]
```diff
@@ -0,0 +1,134 @@
...
+
+bool AtomDownloadManagerDelegate::ShouldOpenDownload(
+    content::DownloadItem* download,
+    const content::DownloadOpenDelayedCallback& callback) {
+  return true;
+}
+
+void AtomDownloadManagerDelegate::GetNextId(
+    const content::DownloadIdCallback& callback) {
+  static uint32 next_id = content::DownloadItem::kInvalidId + 1;
```
Comment (zcbenz) [inline atom/browser/atom_download_manager_delegate.cc]: Using the same ID for all downloads is going to cause troubles.

File: atom/browser/atom_download_manager_delegate.h [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+  bool DetermineDownloadTarget(
+      content::DownloadItem* download,
+      const content::DownloadTargetCallback& callback) override;
+  bool ShouldOpenDownload(
+      content::DownloadItem* download,
+      const content::DownloadOpenDelayedCallback& callback) override;
+  void GetNextId(const content::DownloadIdCallback& callback) override;
+
+ private:
+  scoped_ptr<content::DownloadManager> download_manager_;
```
Comment (zcbenz) [inline atom/browser/atom_download_manager_delegate.h]: `content::DownloadManager` is managed by `BrowserContext`.

File: atom/browser/atom_download_manager_delegate.cc [hunk 6]
```diff
@@ -0,0 +1,134 @@
...
+  callback.Run(next_id++);
```
Comment (deepak1556) [inline atom/browser/atom_download_manager_delegate.cc]: `next_id` incremented before callback here.

Comment (zcbenz) [inline atom/browser/atom_download_manager_delegate.cc]: Oops, I missed the `static` keyword.

Comment (deepak1556) [inline atom/browser/atom_download_manager_delegate.cc]: have addressed the other points, thanks!

**Comment by zcbenz** [comment]
:+1:

**Comment by afocus** [comment]
I am +1 on download api,

**Comment by deadlyicon** [comment]
What do I have to do to get this?
