### PR TITLE
browser: switch to set minimum version for TLS fallback

### LINKED ISSUE #2849: Unable to use https through proxy
Electron 0.32 updated to Chrome 45, and Chrome 45 makes SSL connection more strict, which prohibits https connection through some http proxy that does't support SSL. The output in terminal showed like this
<pre>
[5823:0919/212509:ERROR:ssl_client_socket_openssl.cc(1060)] handshake failed; returned -1, SSL error code 1, net_error -100
</pre>
The app worked properly on Electron 0.31, is it possible to let the app access resources without https anyway?
What's more, for chrome, this terminal command works:
<pre>
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --ssl-version-max=tls1
</pre>
but it doesn't works on electron

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #2849 

Depends on https://github.com/atom/brightray/pull/143

### CODE REVIEW

File: atom/browser/atom_browser_context.cc [hunk 1]
```diff
@@ -156,6 +157,12 @@ content::BrowserPluginGuestManager* AtomBrowserContext::GetGuestManager() {
   return guest_manager_.get();
 }
 
+net::SSLConfigService* AtomBrowserContext::CreateSSLConfigService() {
+  if (!ssl_config_service_)
+    ssl_config_service_.reset(new AtomSSLConfigService);
+  return ssl_config_service_.get();
```
Comment (zcbenz) [inline atom/browser/atom_browser_context.cc]: I think the ownership of `ssl_config_service_` should be transferred to `URLRequestContextGetter`?

File: atom/common/options_switches.cc [hunk 2]
```diff
@@ -113,6 +113,10 @@ const char kDisableHttpCache[] = "disable-http-cache";
 // Register schemes to standard.
 const char kRegisterStandardSchemes[] = "register-standard-schemes";
 
+// The minimum SSL/TLS version ("tls1", "tls1.1", or "tls1.2") that
+// TLS fallback will accept.
+const char kSSLVersionFallbackMin[] = "ssl-version-fallback-min";
```
Comment (zcbenz) [inline atom/common/options_switches.cc]: The original issue seems to ask for `--ssl-version-max`.

Comment (deepak1556) [inline atom/common/options_switches.cc]: i believe providing `ssl-version-max` is not the right one, as chromium already fallbacks with lesser TLS versions for buggy servers but since chromium 44 the fallback version was restricted to "tls1.1" , so this should enable to set a lower fallback https://www.chromium.org/administrators/policy-list-3#SSLVersionFallbackMin

File: atom/browser/atom_browser_context.cc (hunk 1 above)
Comment (deepak1556) [inline atom/browser/atom_browser_context.cc]: Fixed, Thanks!

File: atom/common/options_switches.cc (hunk 2 above)
Comment (zcbenz) [inline atom/common/options_switches.cc]: Can you verify whether `ssl-version-fallback-min` does the job? I don't mind which one is more correct, but the OP only verified `ssl-version-max` works and I'm not sure whether `ssl-version-fallback-min` does.

**Comment by gnattu** [comment]
Tested on original Chrome 45, both <code>ssl-version-fallback-min</code> and <code>ssl-version-max</code> works, since the default TLS version is higher than the max value, Chrome will fallback a lower TLS version anyway.

**Comment by zcbenz** [comment]
:+1:
