### PR TITLE
protocol: cleanup

### LINKED ISSUE #182: Remove locks used by protocol module
The protocol module is calling networking related functions on the UI thread, and we had used locks to make sure no race condition happens. This is dangerous and error-prone (and had caused a crash), we would throw all networking jobs to the IO thread and get rid of the locks.

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #182 

- [x] need to convert `JsProtocolHandler -> (error, request)` which would get rid of those `node::ThrowError` and have uniform async api, will have a wrappedCallback to avoid breaking existing api.

### CODE REVIEW

**Comment by steelbrain** [comment]
Can't wait for the protocol handlers to be async. :heart:

File: atom/browser/api/atom_api_protocol.cc [hunk 1]
```diff
@@ -202,13 +202,42 @@ Protocol::JsProtocolHandler Protocol::GetProtocolHandler(
...
+                                  const JsProtocolHandler& callback,
+                                  bool is_handled) {
+  if (is_handled)
+    return node::ThrowError(isolate(), "The scheme is already registered");
+
+  protocol_handlers_[scheme] = callback;
+  BrowserThread::PostTask(BrowserThread::IO,
+                          FROM_HERE,
+                          base::Bind(&Protocol::RegisterProtocolInIO,
+                                    base::Unretained(this), scheme));
```
Comment (zcbenz) [inline atom/browser/api/atom_api_protocol.cc]: This line is not aligned, actually no `base::Bind` call is aligned.

File: atom/browser/api/atom_api_protocol.cc [hunk 2]
```diff
@@ -202,13 +202,42 @@ Protocol::JsProtocolHandler Protocol::GetProtocolHandler(
...
+}
+
+void Protocol::OnInterceptProtocol(const std::string& scheme,
+                                  const JsProtocolHandler& callback,
```
Comment (zcbenz) [inline atom/browser/api/atom_api_protocol.cc]: Not aligned neither.

File: atom/browser/api/lib/protocol.coffee [hunk 3]
```diff
@@ -6,6 +6,9 @@ EventEmitter = require('events').EventEmitter
 
 protocol.__proto__ = EventEmitter.prototype
 
+protocol.isHandledProtocol = (scheme, callback) ->
```
Comment (zcbenz) [inline atom/browser/api/lib/protocol.coffee]: I don't think we need the JavaScript wrapper here.

File: atom/browser/api/atom_api_protocol.cc [hunk 4]
```diff
@@ -216,15 +245,13 @@ mate::ObjectTemplateBuilder Protocol::GetObjectTemplateBuilder(
 void Protocol::RegisterProtocol(v8::Isolate* isolate,
                                 const std::string& scheme,
                                 const JsProtocolHandler& callback) {
-  if (ContainsKey(protocol_handlers_, scheme) ||
-      job_factory_->IsHandledProtocol(scheme))
+  if (ContainsKey(protocol_handlers_, scheme))
     return node::ThrowError(isolate, "The scheme is already registered");
```
Comment (zcbenz) [inline atom/browser/api/atom_api_protocol.cc]: We should not throw error in asynchronous APIs.

**Comment by deepak1556** [comment]
@zcbenz fixed. Right now the apis are

```
protocol.registerProtocol(scheme, function(error, result))
protocol.interceptProtocol(scheme, function(error, result))
protocol.isHandledProtocol(scheme, function(result))
```

should these be made compatible with older api ?

File: atom/browser/api/atom_api_protocol.cc [hunk 5]
```diff
@@ -202,6 +207,51 @@ Protocol::JsProtocolHandler Protocol::GetProtocolHandler(
...
 
+void Protocol::OnRegisterProtocol(const std::string& scheme,
+                                  const JsProtocolHandler& callback,
+                                  bool is_handled) {
+  DCHECK_CURRENTLY_ON(BrowserThread::UI);
+  v8::Locker locker(isolate());
+  v8::HandleScope handle_scope(isolate());
+
+  if (is_handled || ContainsKey(protocol_handlers_, scheme)) {
+    callback.Run(v8::Exception::Error(
```
Comment (deepak1556) [inline atom/browser/api/atom_api_protocol.cc]: @zcbenz is this right way to create `Error` object ?

Comment (zcbenz) [inline atom/browser/api/atom_api_protocol.cc]: Yeah.

**Comment by zcbenz** [comment]
> should these be made compatible with older api ?

We should keep compatibility with the `register/unregister` and `intercept/unintercept` APIs,

**Comment by zcbenz** [comment]
The APIs should be like:

```coffeescript
hander = (request) ->
  return new protocol.RequestJob
done = ->
  console.log 'protocol is registered'
protocol.registerProtocol('http', handler, done);
```

Having `handler` doing two jobs is not good.

**Comment by deepak1556** [comment]
> Having handler doing two jobs is not good.

:+1:  will have the done callback take a error parameter.

File: atom/browser/api/atom_api_protocol.cc (hunk 5 above)
Comment (deepak1556) [inline atom/browser/api/atom_api_protocol.cc]: but it returns an empty object on JS.

File: atom/browser/api/atom_api_protocol.cc [hunk 6]
```diff
@@ -202,42 +202,89 @@ Protocol::JsProtocolHandler Protocol::GetProtocolHandler(
...
 
+void Protocol::OnRegisterProtocol(const std::string& scheme,
+                                  const JsProtocolHandler& handler,
+                                  const JsCompletionCallback& callback,
+                                  int is_handled) {
+  DCHECK_CURRENTLY_ON(BrowserThread::UI);
+  v8::Locker locker(isolate());
+  v8::HandleScope handle_scope(isolate());
+
+  if (is_handled || ContainsKey(protocol_handlers_, scheme)) {
```
Comment (zcbenz) [inline atom/browser/api/atom_api_protocol.cc]: Since we are going to remove all locks, we should read/write `protocol_handlers_` in IO thread, in case of race conditions.

File: atom/browser/api/atom_api_protocol.cc [hunk 7]
```diff
@@ -202,42 +202,89 @@ Protocol::JsProtocolHandler Protocol::GetProtocolHandler(
...
-    return node::ThrowError(isolate, "The scheme is already registered");
-
-  protocol_handlers_[scheme] = callback;
-  BrowserThread::PostTask(BrowserThread::IO,
-                          FROM_HERE,
-                          base::Bind(&Protocol::RegisterProtocolInIO,
-                                     base::Unretained(this), scheme));
+                                const JsProtocolHandler& handler,
+                                const JsCompletionCallback& callback) {
+  IsHandledProtocol(scheme,
```
Comment (zcbenz) [inline atom/browser/api/atom_api_protocol.cc]: We should checking whether protocol can be registered when trying to register it in IO thread, calling IsHandledProtocol would make call jump from UI => IO => UI => IO, which is quite inefficient.

**Comment by deepak1556** [comment]
@zcbenz have made the changes, thanks!

File: atom/browser/api/atom_api_protocol.cc [hunk 8]
```diff
@@ -189,6 +188,33 @@ class CustomProtocolHandler : public ProtocolHandler {
   DISALLOW_COPY_AND_ASSIGN(CustomProtocolHandler);
 };
 
+std::string ConvertErrorCode(int error_code) {
+  switch (error_code) {
+    case Protocol::ERR_SCHEME_REGISTERED:
+      return "The Scheme is already registered";
+      break;
```
Comment (zcbenz) [inline atom/browser/api/atom_api_protocol.cc]: There is no need to call `break` after `return`.

**Comment by zcbenz** [comment]
The new implementation looks awesome! :+1:

File: atom/browser/api/atom_api_protocol.cc (hunk 8 above)
Comment (deepak1556) [inline atom/browser/api/atom_api_protocol.cc]: Oops, fixed. Thanks!

**Comment by frankhale** [comment]
@deepak1556 THANK YOU!

@zcbenz, you are on fire tonight. It doesn't get said enough... THANK YOU for all that you are doing for Electron!
