### PR TITLE
window: adding setBounds and getBounds api

### LINKED ISSUE #1445: Flash of window in wrong position when using setSize and setPosition
In order to overcome some of the limitations with transparency we've been resizing windows dynamically depending on the content. One thing that we've run into is when attempting to resize from the right instead of the left - you have to do something like the following:

```javascript
browserWindow.setSize(100,500);
browserWindow.setPosition(screenWidth-100, 0);
```

This results in a flash as the window size is changed, rendered, and then moved. It would be **GREAT** to have access to (optionally) [set the origin](https://github.com/atom/electron/blob/master/atom/browser/native_window_mac.mm#L483) when setting the size of a window. This would benefit folks whenever there is a need to move and resize a window in one operation.

I believe this could be added in a backwards compatible manner through a second/third argument to the setSize method, something like:

```javascript
browserWindow.setSize(100, 500, 0, 0);
```

thoughts?

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #1445

### CODE REVIEW

File: atom/browser/native_window_mac.mm [hunk 1]
```diff
@@ -470,6 +470,15 @@ - (void)drawRect:(NSRect)dirtyRect {
   return [window_ styleMask] & NSFullScreenWindowMask;
 }
 
+void NativeWindowMac::SetBounds(const gfx::Rect& bounds) {
+  Move(bounds);
```
Comment (zcbenz) [inline atom/browser/native_window_mac.mm]: It seems that `NativeWindow::Move` is actually the `NativeWindow::SetBounds`, I think we can just do a function rename instead of adding a new one.

File: atom/browser/native_window_mac.mm [hunk 2]
```diff
@@ -470,6 +470,15 @@ - (void)drawRect:(NSRect)dirtyRect {
...
+}
+
+gfx::Rect NativeWindowMac::GetBounds() {
+  return gfx::Rect(GetPosition(),
```
Comment (zcbenz) [inline atom/browser/native_window_mac.mm]: We can probably implement `GetBounds` with Cocoa, and then implement `GetPosition` and `GetSize` with `GetBounds` to make code more decent.

File: atom/browser/native_window_views.cc [hunk 3]
```diff
@@ -373,6 +373,14 @@ bool NativeWindowViews::IsFullscreen() const {
   return window_->IsFullscreen();
 }
 
+void NativeWindowViews::SetBounds(const gfx::Rect& bounds) {
+  window_->SetBoundsConstrained(bounds);
+}
+
+gfx::Rect NativeWindowViews::GetBounds() {
+  return window_->GetRestoredBounds();
```
Comment (zcbenz) [inline atom/browser/native_window_views.cc]: Windows and other platforms are treated differently, you can reference how  `GetSize` was implemented.

**Comment by deepak1556** [comment]
Fixed, have to test on linux and windows.

**Comment by zcbenz** [comment]
Awesome, thanks!

**Comment by tommoor** [comment]
Many thanks, looking forward to release :smile:
