### PR TITLE
webContents: override fullscreen notification apis for webview

### LINKED ISSUE #1503: HTML5 fullscreen api not working in webview-tag
Hi 
I just pulled the master and tried the new fullscreen feature.
It works perfect as long as the video is not embedded inside a webview.
Is it possible to fix this?

-Tobias

### LINKED ISSUE #1627: Fullscreen exits when calling loadUrl, 0.25.2 on Windows
It appears there was a bug introduced in 0.25.2 with the BrowserWindow class.
With the following code:
```
@window.loadUrl(targetUrl);
@window.setFullScreen(true);
@window.show();
```
The call to ```loadUrl``` will always exit the window out of fullscreen mode. If you call ```setFullScreen``` before ```loadUrl```, the window will enter fullscreen mode for a moment and then also exit out. Without a ```loadUrl``` call, the window stays in fullscreen mode.

This behavior was noted on Windows using electron-ia32 on 0.25.2 and above - have looked into changes introduced in 0.25.2 and have not noticed anything obvious that would cause this.

### LINKED ISSUE #1721: Fullscreen not working anymore on linux x64 with v0.26?
The following BrowserWindow config does not appear in fullscreen anymore in ubuntu 14.04:

```
{ show: true,
  resizable: false,
  frame: false,
  'enable-larger-than-screen': true,
  'node-integration': false,
  'web-preferences': { plugins: true },
  'always-on-top': true,
  kiosk: true,
  fullscreen: true }
```

Tested with `v0.26`, used to work with `v0.23`

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #1503 
Fixes #1721 
Fixes #1627

### CODE REVIEW

**Comment by deepak1556** [comment]
Also addresses https://github.com/atom/electron/issues/1503#issuecomment-102312614

**Comment by deepak1556** [comment]
@thyrrestrup have addressed issue 1 , regarding issue 2 html fullscreen works by triggerring the window to go fullscreen, then webcontents resizes to occupy the available space. So to answer your questions

> Is it possible to create a completely new window for the video content and assign it a window level above the fullscreen browser window?

nope not possible on electron side.

> and also to only include the webview that contains the video?

Since webview is the window bound for the contents inside it, if the webview got resized correctly to occupy the complete window then video element would have be resized correctly.

**Comment by thyrrestrup** [comment]
@deepak1556 - Awesome. I'm wondering if it's possible to emit a event before entering html5 fullscreen and when exiting html5 fullscreen? Then I can hide/unhide other webviews.

**Comment by deepak1556** [comment]
Have added `enter-html-full-screen` and `exit-html-full-screen` events.

**Comment by thyrrestrup** [comment]
This is perfect thank you.

**Comment by thyrrestrup** [comment]
@deepak1556 - When leaving fullscreen html the browser window is also taken out of fullscreen.

**Comment by thyrrestrup** [comment]
@deepak1556 - I made the fullscreen work like this:
```c++
// native_window.cc
bool NativeWindow::IsFullscreenForTabOrPending(
    const content::WebContents* source) const {
  return IsFullscreen();
}
...
void NativeWindow::SetHtmlApiFullscreen(bool enter_fullscreen) {
    if (enter_fullscreen) {
        if(IsFullscreen()) {
            fullscreen_ = false;
        } else {
            fullscreen_ = true;
            SetFullScreen(true);
        }
    } else {
        if (fullscreen_) {
            fullscreen_ = false;
            SetFullScreen(false);
        }
    }
}
```
```c++
// atom_api_web_contents.cc
bool WebContents::IsFullscreenForTabOrPending(
    const content::WebContents* source) const {
  auto window = GetWindowFromGuest(source);
  if (window)
    return window->IsFullscreen();
  else
    return false;
}
```

And maybe the events should be emitted from the `SetHtmlApiFullscreen()` function?

**Comment by thyrrestrup** [comment]
@deepak1556 - I solved the issue with this code:
```c++
// native_window.h
  bool html_fullscreen_;

// native_window.cc
NativeWindow::NativeWindow(content::WebContents* web_contents,
                           const mate::Dictionary& options)
    : content::WebContentsObserver(web_contents),
// ...
      html_fullscreen_(false),
// ...

void NativeWindow::SetHtmlApiFullscreen(bool enter_fullscreen) {
    if(!IsFullscreen()) {
        html_fullscreen_ = true;
    }
    if(html_fullscreen_) {
        html_fullscreen_ = enter_fullscreen;
        SetFullScreen(enter_fullscreen);
    }
    fullscreen_ = enter_fullscreen;
}
```

I think maybe the events need to be emitted from `SetHtmlApiFullscreen()` because it is used by both window and web contents.

**Comment by deepak1556** [comment]
@thyrrestrup sorry about that, yeah forgot to implement event for `webcontents`. Will fix them, thanks

**Comment by deepak1556** [comment]
@thyrrestrup have fixed them. can you confirm if it works as expected ?

**Comment by thyrrestrup** [comment]
@deepak1556 - It works beautifully ;-) Thanks!

You could shorten it a bit if you initialise `forced_fullscreen_` to false and then do:
```c++
void NativeWindow::SetHtmlApiFullscreen(bool enter_fullscreen) {
  if (forced_fullscreen_ || !IsFullscreen()) {
      forced_fullscreen_ = enter_fullscreen;
      SetFullScreen(enter_fullscreen);
  }
  html_fullscreen_ = enter_fullscreen;
}
```

**Comment by MikeGCV** [comment]
builded with these patches, problem seems solved but the fullscreen flag doesn't work, only when setFullScreen(true) is executed the app goes full screen

**Comment by deepak1556** [comment]
@MikeGCV does your `browser-window` configuration have both kiosk and fullscreen flags set to `true` ?

**Comment by deepak1556** [comment]
@MikeGCV the reason for either having only `kiosk` or `fullscreen` flag not working is different cause in `desktop_window_tree_host_x11::MapWindow` function and not introduced by html api, working on a fix for it. For now you can workaround by setting both of them to `true` in the configuration.

**Comment by MikeGCV** [comment]
Tested on ubuntu 15.04 x64 with kiosk and fullscreen flags, no fullscreen, just with setFullScreen(true).Not a big problem, maybe i didn't apply all the patches

File: atom/browser/api/atom_api_web_contents.cc [hunk 1]
```diff
@@ -215,6 +215,34 @@ void WebContents::HandleKeyboardEvent(
       web_contents(), event);
 }
 
+void WebContents::EnterFullscreenModeForTab(content::WebContents* source,
+                                            const GURL& origin) {
+  auto window = GetWindowFromGuest(source);
+  if (window) {
+    window->SetHtmlApiFullscreen(true);
+    source->GetRenderViewHost()->WasResized();
+    Emit("enter-html-full-screen");
```
Comment (zcbenz) [inline atom/browser/api/atom_api_web_contents.cc]: I think `BrowserWindow` should also emit `enter-html-full-screen` when its webview enters fullscreen?

File: atom/browser/native_window.cc [hunk 2]
```diff
@@ -805,6 +810,25 @@ void NativeWindow::ScheduleUnresponsiveEvent(int ms) {
       base::TimeDelta::FromMilliseconds(ms));
 }
 
+void NativeWindow::SetHtmlApiFullscreen(bool enter_fullscreen) {
```
Comment (zcbenz) [inline atom/browser/native_window.cc]: The definition of member functions should be placed in the same order with their declarations.

File: atom/browser/native_window.cc [hunk 3]
```diff
@@ -805,6 +810,25 @@ void NativeWindow::ScheduleUnresponsiveEvent(int ms) {
...
+  // Window is already in fullscreen mode, save the state.
+  if (enter_fullscreen && IsFullscreen()) {
+    forced_fullscreen_ = true;
+    html_fullscreen_ = true;
+    return;
+  }
+
+  // Exit html fullscreen state but not window's fullscreen mode.
+  if (!enter_fullscreen && forced_fullscreen_) {
```
Comment (zcbenz) [inline atom/browser/native_window.cc]: Why do we want to keep window's fullscreen mode when user requests to quit fullscreen?

File: atom/browser/native_window.h [hunk 4]
```diff
@@ -217,6 +220,8 @@ class NativeWindow : public brightray::DefaultWebContentsDelegate,
 
   bool has_frame() const { return has_frame_; }
 
+  bool IsHtmlApiFullscreen() const { return html_fullscreen_; }
```
Comment (zcbenz) [inline atom/browser/native_window.h]: `IsHtmlApiFullscreen` => `is_html_api_fullscreen` since it is an inline getter.

File: atom/browser/native_window.h [hunk 5]
```diff
@@ -343,6 +348,12 @@ class NativeWindow : public brightray::DefaultWebContentsDelegate,
   // There is a dialog that has been attached to window.
   bool has_dialog_attached_;
 
+  // Whether window is fullscreened by HTML5 api.
+  bool html_fullscreen_;
+
+  // Whether window is fullscreened by window api.
+  bool forced_fullscreen_;
```
Comment (zcbenz) [inline atom/browser/native_window.h]: It should be initialized in the constructor,

File: atom/browser/native_window.cc (hunk 3 above)
Comment (thyrrestrup) [inline atom/browser/native_window.cc]: If the browser window is set with fullscreen:true or kiosk:true we only want to exit the html full screen context and not the window.

Comment (zcbenz) [inline atom/browser/native_window.cc]: I think if we want to exit the html fullscreen we have to enter the html fullscreen first?

Previously entering html fullscreen will be prevented if the window is already in fullscreen, but it has been fixed in this PR.

Comment (thyrrestrup) [inline atom/browser/native_window.cc]: Yes and it works as expected in this PR.
If the window is already in fullscreen when the html context wants fullscreen we just allow the html to go fullscreen without changing the window state. And when the html context wants to exit fullscreen we check to see if the window state was changed on entering html fullscreen if not we just leave it as it is.

File: atom/browser/api/atom_api_web_contents.cc (hunk 1 above)
Comment (deepak1556) [inline atom/browser/api/atom_api_web_contents.cc]: :+1:

File: atom/browser/native_window.cc (hunk 3 above)
Comment (deepak1556) [inline atom/browser/native_window.cc]: @zcbenz just following chrome's behaviour here.

Comment (zcbenz) [inline atom/browser/native_window.cc]: It makes sense now, thanks for clarifying it. Maybe we can rename `forced_fullscreen_` to `already_in_fullscreen_` to make the logic clearer.

Comment (deepak1556) [inline atom/browser/native_window.cc]: Is `native_fullscreen_` better ?

Comment (zcbenz) [inline atom/browser/native_window.cc]: :+1:

**Comment by deepak1556** [comment]
@zcbenz fixed, thanks!
