### PR TITLE
Don't crash when IPC channel is missing

### LINKED ISSUE #4427: calling webContents.send(undefined) causes the process to end
Calling `webContents.send(undefined)` causes the process to end with no exception or error.

I guess it could be fixed with

```js
if (channel == null) {
    throw new Error("Channel is a mandatory argument");
}
```

in the send javascript code.

### PR DESCRIPTION
**Pull request by kevinsawicki**
Throw an explicit error instead about the channel being required.

This pull request also formats the `BrowserWindow` spec from the CoffeeScript migration.

Closes #4427

### CODE REVIEW

File: atom/browser/api/lib/web-contents.js [hunk 1]
```diff
@@ -76,8 +76,11 @@ let wrapWebContents = function(webContents) {
 
   // WebContents::send(channel, args..)
   webContents.send = function() {
-    var args, channel;
-    channel = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
+    var args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
+    var channel = arguments[0];
+    if (channel == null) {
```
Comment (steelbrain) [inline atom/browser/api/lib/web-contents.js]: How about `(!channel)`, it'll then also catch falsy values like undefined

Comment (steelbrain) [inline atom/browser/api/lib/web-contents.js]: Nevermind, noticed `==` instead of `===`
