### PR TITLE
Fix calculating min/max size in frameless view

### LINKED ISSUE #1806: BrowserWindow min-width and min-height not set consistently with width and height properties
I'm seeing two problems with the min-width and min-height properties.

First, when opening a window that includes the native window chrome, the window width and height that is set when creating the window includes the width and height of the native window chrome.  So if I set width to 800px and height to 600px, the entire window is 800 x 600.  However, if we also set min-width to 800px and min-height to 600px, these measurements seem to exclude the native chrome.  So if I try to resize it at all (or even to drag the window on Windows), it will resize itself so that the contents (excluding the chrome) are 800 x 600.  The window will get bigger by the size of the chrome, which is the height of the header on OSX and about 15px x 38px on Windows.

Secondly, on Windows only, if you have auto-scaling turned on, this is being applied once when opening the BrowserWindow with a specified width and height, but is being applied a second time when evaluating min-width and min height. For example, my PC has a screen resolution of 3200 x 1800, and the recommended scaling is 200%.  With these settings, if we create a browser window as 400px wide and 300px high, then it's actually created as 800 x 600, which is what I'd expect with 200% scaling.  However, it seems that if I also set the min-width to 400 and the min-height to 300, and drag or attempt to resize the window, then the minimum dimensions are evaluated, and doubled again, so I end up with a window that jumps to twice the expected size (1626 x 1271).  While I can get around this by turning off auto-scaling (setting scaling to 100%), because the recommended setting for my resolution is to have this turned on, I would expect that a lot of Windows users with high-resolution monitors would run into a similar problem.

Thank you.

### LINKED ISSUE #2945: BrowserWindow height and min-height options vary based on title bar
Electron v0.33.1 on Mac OS X 10.10.5

The `height` and `min-height` options for BrowserWindow appear to be behaving inconsistently, in that `min-height` appears to take into account the size of the title bar.

To see this happen, use the following app code.  Once open, attempt to resize slightly using the bottom corner, and notice that the window snaps its height to be slightly larger than it was initially, despite the `height` and `min-height` both being initialized to `400`.

```js
var app = require('app');
var BrowserWindow = require('browser-window');
app.on('ready', function () {
  var win = new BrowserWindow({
    height: 400,
    width: 400,
    'min-height': 400
  });
  win.show();
});
```

### PR DESCRIPTION
**Pull request by etiktin**
The minimum size and maximum size that frameless view used, were incorrect. The sizes are treated as if they don't include border, but they did so it actually increased the window size on resize (see the reproduction code in #2945). The fix was to normalize the sizes from window size to frameless size (removing border etc.).

This resolves #2945. ~~It also partially fixes #1806. The reason I say partially is because the issue also mention some issues with hidpi, and I'm not sure if this fixes that as well.~~
*Edit:* It also resolves #1806. At first I wasn't sure it also solved the second issue mentioned there about resizing when in hidpi doubling window size, but I manged to test it using `--force-device-scale-factor=2` and it seems to have solve it.

This code was only tested on Windows. If it doesn't work on Linux or OS X, we can easily make it work only for Windows by moving the code from `frameless_view.cc` to `win_frame_view.cc`.

### CODE REVIEW

**Comment by zcbenz** [comment]
The way Linux implements frameless window is quite different from Windows, so I think we should only use this code on Windows.

File: atom/browser/native_window_views.cc [hunk 1]
```diff
@@ -874,6 +872,33 @@ void NativeWindowViews::HandleSizeEvent(WPARAM w_param, LPARAM l_param) {
...
+    return size;
+
+  gfx::Rect window_bounds = gfx::Rect(size);
+  if (use_content_size_) {
+    if (menu_bar_ && menu_bar_visible_) {
+      window_bounds.set_height(window_bounds.height() + kMenuBarHeight);
+    }
+  } else if (has_frame()) {
+#if defined(OS_WIN)
+  gfx::Size frame_size = gfx::win::ScreenToDIPRect(
```
Comment (zcbenz) [inline atom/browser/native_window_views.cc]: The `WinFrameView::GetMinimumSize` calls `gfx::win::DIPToScreenSize` for the passed size, maybe we should just remove the call there? So we don't need to convert screen size to DPI size and then convert back.

**Comment by etiktin** [comment]
@zcbenz, #2945 and #1806, mention that this issue occurs in OS X and Windows (don't know if it happens on Linux as well). So before we limit the solution just to Windows, I think we should check if it works also for OS X and Linux.
I don't have access to OS X and Linux so I can't test it myself. Can anyone else test it on those platforms (you can reproduce the issue using the code from #2945)?

**Comment by etiktin** [comment]
I changed it to work on Windows only.

The issue also exists on OS X (as mentioned in #2945 and #1806). I believe the solution will be similar (normalizing the min/max size using `WindowSizeToFramelessSize` in the relevant views), but since I can't test it (no access to a Mac) I'll leave it to someone else.

By the way, on Windows at least, the fix works for windows with or without a frame.

File: atom/browser/ui/views/win_frame_view.cc [hunk 2]
```diff
@@ -40,12 +40,14 @@ int WinFrameView::NonClientHitTest(const gfx::Point& point) {
 }
 
 gfx::Size WinFrameView::GetMinimumSize() const {
-  gfx::Size size = FramelessView::GetMinimumSize();
+  gfx::Size size = window_->WindowSizeToFramelessSize(
+      window_->GetMinimumSize());
```
Comment (etiktin) [inline atom/browser/ui/views/win_frame_view.cc]: I'm using ` window_->GetMinimumSize()` instead of `FramelessView::GetMinimumSize()`, to prevent potential issues, if we end up using `WindowSizeToFramelessSize` in `FramelessView` for OS X or Linux (the problem that comes to mind is that we'll remove the frame size twice).

This is true also for the `GetMaximumSize` code below.

**Comment by zcbenz** [comment]
:+1:
