### PR TITLE
Fix dialog.showSaveDialog doesn't show the non-exist file name on Linux.

### LINKED ISSUE #1855: dialog.showSaveDialog default filename for files that do not exist.
This is related to #1541 

I am using Linux 64bit, electron, version 0.26.1.

dialog.showSaveDialog cannot be passed a filename for a file that does not exist yet. This seems strange, as typically if you are saving/downloading a file using a file picker, it's because you don't have the file yet.

The call I was using:

```
var downloadPath = dialog.showSaveDialog({defaultPath: filename});
event.returnValue = downloadPath ? downloadPath : null;
```

### PR DESCRIPTION
**Pull request by hokein**
Fixes #1855 .
This patch makes the `default_path` parameter behave samely on three platforms.

### CODE REVIEW

File: atom/browser/ui/file_dialog_gtk.cc [hunk 1]
```diff
@@ -96,9 +96,12 @@ class FileChooserDialog {
       if (base::DirectoryExists(default_path))
         gtk_file_chooser_set_current_folder(GTK_FILE_CHOOSER(dialog_),
                                             default_path.value().c_str());
-      else
-        gtk_file_chooser_set_filename(GTK_FILE_CHOOSER(dialog_),
-                                      default_path.value().c_str());
+      else {
```
Comment (zcbenz) [inline atom/browser/ui/file_dialog_gtk.cc]: > atom/browser/ui/file_dialog_gtk.cc:99:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]

Comment (hokein) [inline atom/browser/ui/file_dialog_gtk.cc]: Done.

**Comment by zcbenz** [comment]
Thanks!
