### PR TITLE
Fix print spooler hangs when printing more than 3 pages on Windows.

### LINKED ISSUE #2627: Printing fails with more than 3 pages on Windows
I'm not able to print out a document with more than three pages on Windows. Debian looks fine.

- System: Windows 7 32-Bit and 64-Bit
- Electron versions: `0.31.1` and `0.30.6`
- Kind of app: Simple `BrowserWindow` to load a website

By using `PDFCreator` the print queue stops at page 3/3, even if there are more pages. I can't recognize any error message.
Printing through a physical printer doesn't display anything and the printer keeps silent.
The size of the document doesn't seem to be a problem, since it happens with both text-only and pictures-only.

Could someone test this please, to exclude a problem with the client?

### PR DESCRIPTION
**Pull request by hokein**
Fixes #2627.

### CODE REVIEW

File: chromium_src/chrome/browser/printing/print_job.cc [hunk 1]
```diff
@@ -375,6 +317,68 @@ void PrintJob::OnPdfToEmfPageConverted(int page_number,
...
+      // This will call Stop() and broadcast a JOB_DONE message.
+      base::MessageLoop::current()->PostTask(
+          FROM_HERE, base::Bind(&PrintJob::OnDocumentDone, this));
+      break;
+    }
+    case JobEventDetails::PAGE_DONE:
+#if defined(OS_WIN)
+      ptd_to_emf_state_->OnPageProcessed(
+          base::Bind(&PrintJob::OnPdfToEmfPageConverted, this));
+#endif  // OS_WIN
```
Comment (hokein) [inline chromium_src/chrome/browser/printing/print_job.cc]: For review easily, the only change of the PR is adding the above 4 lines. The `pdf_to_emf_state_` requires to see the definition of `PdfToEmfState` class.

**Comment by zcbenz** [comment]
Thanks!
