### PR TITLE
common: export hideInternalModules

### LINKED ISSUE #4219: hideInternalModules() throws error
When calling `require('electron').hideInternalModules();` in the main process (not tested in renderer process), it throws an error.

```
Uncaught Exception:
TypeError: require(...).hideInternalModules is not a function
    at Object.<anonymous> (PRIVATE_PATH\build\browser\bootstrap.js:4:21)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (PRIVATE_PATH\node_modules\electron-prebuilt\dist\resources\default_app\main.js:258:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

Electron Version: 0.36.5

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #4219

### CODE REVIEW

File: atom/common/api/lib/exports/electron.js [hunk 1]
```diff
@@ -11,6 +11,12 @@ exports.hideInternalModules = function() {
 // Attaches properties to |exports|.
 exports.defineProperties = function(exports) {
   return Object.defineProperties(exports, {
+    hideInternalModules: {
+      enumerable: true,
+      get: function() {
```
Comment (zcbenz) [inline atom/common/api/lib/exports/electron.js]: Probably just use `value`.

Comment (deepak1556) [inline atom/common/api/lib/exports/electron.js]: Fixed.

**Comment by zcbenz** [comment]
:+1:
