### PR TITLE
nativemate: use maybe version of v8::Function::call to avoid unhandled exceptions

### LINKED ISSUE #3193: app.makeSingleInstance(): Received signal 11 SEGV_MAPERR 000000000000
I am playing around with app.makeSingleInstance() and I see the following output when my callback has a runtime exception (e.g. nullpointer):

Received signal 11 SEGV_MAPERR 000000000000
 [0x000108bad6d7]
 [0x7fff872f5f1a]
 [0x7fff571d2270]
 [0x000108b2f585]
 [0x000108a409a8]
 [0x000108a40ed5]
 [0x000108a40e28]
 [0x000108a40da2]
 [0x000108a3930c]
 [0x000108a37759]
 [0x000108a3d41e]
 [0x000108a3d3b4]
 [0x000108a3d360]
 [0x000108a3930c]
 [0x000108b11749]
 [0x000108b153b9]
 [0x000108b15310]
 [0x000108b15295]
 [0x000108badc12]
 [0x000108bcbddf]
 [0x000108bcc1c6]
 [0x000108ba4821]
 [0x000108bc411a]
 [0x000108ba4224]
 [0x7fff8e796a01]
 [0x7fff8e788b8d]
 [0x7fff8e7881bf]
 [0x7fff8e787bd8]
 [0x7fff8444156f]
 [0x7fff844412ea]
 [0x7fff8444112b]
 [0x7fff866988ab]
 [0x7fff86697e58]
 [0x7fff8668daf3]
 [0x000108ba5051]
 [0x000108ba466c]
 [0x000108bdb1d3]
 [0x00010909a84b]
 [0x00010909a785]
 [0x00010909cc32]
 [0x000109096adf]
 [0x0001090209dc]
 [0x000109020036]
 [0x000108a3318d]
 [0x000108a2beea]
 [0x7fff89ea45c9]
 [0x000000000002]

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #3193

### CODE REVIEW

File: atom/common/native_mate_converters/callback.h [hunk 1]
```diff
@@ -72,8 +72,14 @@ struct V8FunctionInvoker<ReturnType(ArgTypes...)> {
...
     ReturnType ret;
     std::vector<v8::Local<v8::Value>> args = { ConvertToV8(isolate, raw)... };
-    v8::Local<v8::Value> val(holder->Call(holder, args.size(), &args.front()));
-    Converter<ReturnType>::FromV8(isolate, val, &ret);
+    v8::Local<v8::Value> result;
+    auto maybe_result =
+        holder->Call(context, holder, args.size(), &args.front());
+    if (!maybe_result.ToLocal(&result)) {
+      static ReturnType defaultType;
+      return defaultType;
```
Comment (zcbenz) [inline atom/common/native_mate_converters/callback.h]: I think we can simply do:

```c++
if (maybe_result.ToLocal(&result))
  Converter<ReturnType>::FromV8(isolate, result, &ret);
```

Comment (deepak1556) [inline atom/common/native_mate_converters/callback.h]: The mac build on travis was throwing `-Wsometime-uninitialised` when i did that https://travis-ci.org/atom/electron/jobs/87215154

Comment (zcbenz) [inline atom/common/native_mate_converters/callback.h]: It can be solved by assigning `ret` a default value when declaring it:

```c++
ReturnType ret = ReturnType();
```

Comment (deepak1556) [inline atom/common/native_mate_converters/callback.h]: Is `ReturnType` guranteed to have a copy constructor ?

Comment (zcbenz) [inline atom/common/native_mate_converters/callback.h]: It is calling `ReturnType`'s default constructor, the requirement of a default constructor has always been there.

Usually `ReturnType ret` is enough for most types, but for built-in types like `int` it results in an uninitialized state and we have to force using default constructor.

Comment (deepak1556) [inline atom/common/native_mate_converters/callback.h]: Thanks for explaining, updated!

**Comment by zcbenz** [comment]
:+1:
